// generated by ./scripts/build.js
export default {
  "firebase": {
    "apiKey": "AIzaSyAH89_R66bOfe3qy1z1Lev0ZjZg6raq6fw",
    "authDomain": "eerc-a5a53.firebaseapp.com",
    "databaseURL": "https://eerc-a5a53.firebaseio.com",
    "projectId": "eerc-a5a53",
    "storageBucket": "eerc-a5a53.appspot.com",
    "messagingSenderId": "1074595049803",
    "appId": "1:1074595049803:web:0e9fb0f0960b41715d78ce",
    "measurementId": "G-NZHPL5DYFW"
  }
}